### ISSUE TITLE
Save multiple responses using Postman runner

### ISSUE THREAD

**Issue by Frodo1980** [sivcan/ResponseToFile-Postman#7]
Hi Sivcan,

thanks for your really great work.

Is ist possible to save the responses of multiple requests using the runner in postman?

Greetings from germany

Michael

**Comment by sivcan** [comment]
@Frodo1980 Yes it is, you can refer the following config:
https://community.postman.com/t/outputting-request-response-pairs-to-file/13531/4

You can keep the script of Postman at the collection level and make sure `uniqueIdentifier` is set as `true` in the `opts`.
This will make sure that every response that gets received during the runner's execution will be stored in a new file with a unique identifier. You can also customize this unique identifier and provide it on your own.

Point 2 under File Support section explains this option: https://github.com/sivcan/ResponseToFile-Postman#file-support
